// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9aFVzWazTDrMFsEHiwoQlBZvZDkLc6H4',
    appId: '1:456271136968:web:7ade63b23296194d79bdfd',
    messagingSenderId: '456271136968',
    projectId: 'daily-messages-db6fb',
    authDomain: 'daily-messages-db6fb.firebaseapp.com',
    storageBucket: 'daily-messages-db6fb.firebasestorage.app',
    measurementId: 'G-5B8R6TBBRN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATLs95mXAuGoNfwYxrBCai-WZz1KmYwUY',
    appId: '1:456271136968:android:49735a6db3dbd8ec79bdfd',
    messagingSenderId: '456271136968',
    projectId: 'daily-messages-db6fb',
    storageBucket: 'daily-messages-db6fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFNWtcy1iW7ggH6vs6GbO7quW2-ArioVo',
    appId: '1:456271136968:ios:19b01465cf361e0679bdfd',
    messagingSenderId: '456271136968',
    projectId: 'daily-messages-db6fb',
    storageBucket: 'daily-messages-db6fb.firebasestorage.app',
    iosBundleId: 'com.example.motivationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFNWtcy1iW7ggH6vs6GbO7quW2-ArioVo',
    appId: '1:456271136968:ios:19b01465cf361e0679bdfd',
    messagingSenderId: '456271136968',
    projectId: 'daily-messages-db6fb',
    storageBucket: 'daily-messages-db6fb.firebasestorage.app',
    iosBundleId: 'com.example.motivationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9aFVzWazTDrMFsEHiwoQlBZvZDkLc6H4',
    appId: '1:456271136968:web:b88f75857a02c28679bdfd',
    messagingSenderId: '456271136968',
    projectId: 'daily-messages-db6fb',
    authDomain: 'daily-messages-db6fb.firebaseapp.com',
    storageBucket: 'daily-messages-db6fb.firebasestorage.app',
    measurementId: 'G-8JL60YLBDT',
  );

}